management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    preferIpAddress: true
    nonSecurePort: 8082

spring:
  application:
    name: sale-api-instance
  data:
    mongodb:
      database: sales
      port: 27018
      host: sale-mongo

server:
  port: 8082
